Fix slabratetop.py for 6.8 kernel
slabratetop.py failed with 6.8 kernel with

  /virtual/main.c:100:10: fatal error: 'linux/slub_def.h' file not found
    100 | #include <linux/slub_def.h>
        |          ^~~~~~~~~~~~~~~~~~
  1 error generated.

Actually 'kmem_cache' is also not available to bcc any more.
We already copied 'slab' data structure to bcc, copying yet
another one (probably with others) will make things too
complex and error prone.

Let us use newly introduced kernel_struct_field_size_offset() API.
We could get some data structure (field, size) information
from kernel BTF. This enables us to work around header file
not available issue.

Signed-off-by: Yonghong Song <yonghong.song@linux.dev>