Fix: error adding symbols: DSO missing from command line
Compile error:

 $ cmake ..
 $ make
 ...
 [ 37%] Linking CXX executable CGroupTest
 /usr/bin/ld: /usr/lib64/libLLVMBPFAsmParser.a(BPFAsmParser.cpp.o): undefined reference to symbol '_ZSt21__glibcxx_assert_failPKciS0_S0_@@LLVM_14'
 /usr/bin/ld: /usr/lib64/libLLVM-14.so: error adding symbols: DSO missing from command line
 collect2: error: ld returned 1 exit status
 make[2]: *** [examples/cpp/CMakeFiles/CGroupTest.dir/build.make:163: examples/cpp/CGroupTest] Error 1
 make[1]: *** [CMakeFiles/Makefile2:1013: examples/cpp/CMakeFiles/CGroupTest.dir/all] Error 2
 make: *** [Makefile:146: all] Error 2

 Need '-shared' during compile.

Signed-off-by: Rong Tao <rongtao@cestc.cn>