fix a compilation issue with latest llvm trunk (9.0) (#2242)
The following llvm change in trunk (9.0)
  https://reviews.llvm.org/D58194
breaks bcc build.

  [ 76%] Building CXX object src/cc/CMakeFiles/bcc-static.dir/bpf_module.cc.o
  /home/yhs/work/bcc/src/cc/bcc_debug.cc: In member function ‘void ebpf::SourceDebugger::dump()’:
  /home/yhs/work/bcc/src/cc/bcc_debug.cc:207:23: error: no matching function for call to ‘llvm::DWARFDebugLine::LineTable::getFileLineInfoForAddress(uint64_t, const char*, llvm::DILineInfoSpecifier::FileLineInfoKind, llvm::DILineInfo&) const’
               LineInfo);
                       ^
  /home/yhs/work/bcc/src/cc/bcc_debug.cc:207:23: note: candidate is:
  In file included from /home/yhs/work/llvm/build/install/include/llvm/DebugInfo/DWARF/DWARFContext.h:24:0,
                   from /home/yhs/work/bcc/src/cc/bcc_debug.cc:22:
  /home/yhs/work/llvm/build/install/include/llvm/DebugInfo/DWARF/DWARFDebugLine.h:253:10: note: bool llvm::DWARFDebugLin
  e::LineTable::getFileLineInfoForAddress(llvm::object::SectionedAddress, const char*, llvm::DILineInfoSpecifier::FileLi
  neInfoKind, llvm::DILineInfo&) const
       bool getFileLineInfoForAddress(object::SectionedAddress Address,

The reason is that function getFileLineInfoForAddress() signature changed.
The first argument used to be "uint64_t" and now "object::SectionedAddress" which
includes both address and section ID.

This patch fixed this issue by specializing getFileLineInfoForAddress() for LLVM 9.
There exists no variant for getFileLineInfoForAddress() working for all LLVM versions.

Signed-off-by: Yonghong Song <yhs@fb.com>