cc: Sync loongarch64 so flags from glibc (#5500)
Synchronize the shared library flag bits for LoongArch64 from glibc to resolve errors in some bcc tools caused by their inability to recognize the libc library.

glibc reference path:  sysdeps/generic/ldconfig.h

Error message:
# /usr/share/bcc/tools/gethostlatency
Traceback (most recent call last):
  File "/usr/share/bcc/tools/gethostlatency", line 106, in <module>
    b.attach_uprobe(name="c", sym="getaddrinfo", fn_name="do_entry", pid=args.pid)
  File "/usr/lib/python3.11/site-packages/bpfcc/__init__.py", line 1410, in attach_uprobe
    (path, addr) = BPF._check_path_symbol(name, sym, addr, pid, sym_off)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bpfcc/__init__.py", line 1008, in _check_path_symbolic_address
    raise Exception("could not determine address of symbol %s in %s"
Exception: could not determine address of symbol getaddrinfo in c

Signed-off-by: zhangzikang01 <zhangzikang@kylinos.cn>