libbpf-tools: fix ksnoop panic
Running ksnoop with an invalid func will cause
panic, testing with glibc 2.35.

Error:
```
$ ./ksnoop info xxx
Error: [1]    41304 segmentation fault (core dumped)  ./ksnoop info xxx
```

Fixed by changing format string to %s.

Signed-off-by: Chen Yaqi <chendotjs@gmail.com>