tools/readahead: Fix: Failed to attach BPF program entry__do_page_cache_readahead
since commit 56a4d67c264e("mm/readahead: Switch to page_cache_ra_order") switch
do_page_cache_ra() to page_cache_ra_order() (v5.17), and commit bb3c579e25e5
("mm/filemap: Add filemap_alloc_folio") swap __page_cache_alloc() to
filemap_alloc_folio() (since v5.15)

Reprocude the error(fedora37, 6.1.7-200.fc37.aarch64):

    $ sudo ./readahead.py
    cannot attach kprobe, probe entry may not exist
    Traceback (most recent call last):
    File "/home/rongtao/Git/bcc/tools/./readahead.py", line 159, in <module>
        b.attach_kprobe(event=ra_event, fn_name="entry__do_page_cache_readahead")
    File "/usr/lib/python3.11/site-packages/bcc/__init__.py", line 840, in attach_kprobe
        raise Exception("Failed to attach BPF program %s to kprobe %s" %
    Exception: Failed to attach BPF program b'entry__do_page_cache_readahead' to kprobe b'do_page_cache_ra'

Signed-off-by: Rong Tao <rongtao@cestc.cn>