Fix llvm compilation failure (#5276)
Upstream patch [1] caused bcc build failure:
  ...
  /home/yhs/work/bcc/src/cc/bcc_debug.cc: In member function ‘void ebpf::SourceDebugger::dump()’:
  /home/yhs/work/bcc/src/cc/bcc_debug.cc:117:43: error: no matching function for call to
      ‘std::__cxx11::basic_string<char>::basic_str’
    117 |   string TripleStr(mod_->getTargetTriple());
        |                                           ^
  ...
  /home/yhs/work/bcc/src/cc/bpf_module.cc: In member function ‘int ebpf::BPFModule::finalize()’:
  /home/yhs/work/bcc/src/cc/bpf_module.cc:546:24: error: cannot convert ‘const char [13]’ to ‘llvm::Triple’
    546 |   mod->setTargetTriple("bpf-pc-linux");
        |                        ^~~~~~~~~~~~~~
        |                        |
        |                        const char [13]
  ...

This patch fixed the above compilation failure.

  [1] https://github.com/llvm/llvm-project/pull/129868