sigsnoop: Get rid of SIGIOT
SIGIOT is an alias of SIGABRT so it's assigned to the same number.
However it caused an error in my build setup like below:

  libbpf-tools/sigsnoop.c:40:8: error: initializer overrides prior
                                initialization of this subobject
				[-Werror,-Winitializer-overrides]
          [6] = "SIGIOT",
                ^~~~~~~~
  libbpf-tools/sigsnoop.c:39:8: note: previous initialization is here
          [6] = "SIGABRT",
                ^~~~~~~~~
  1 error generated.

Anyway, it's gonna show only single entry.  So let's remove the other.