libbpf-tools: Fix ext4dist compilation
Fix compilation error because of un-initialized global variable:

bin/bpftool gen skeleton .output/ext4dist.bpf.o > .output/ext4dist.skel.h
libbpf: invalid relo for 'hists' in special section 0xfff2; forgot to initialize global var?..
Error: failed to open BPF object file: Relocation failed
make: *** [Makefile:89: .output/ext4dist.skel.h] Error 255
make: *** Deleting file '.output/ext4dist.skel.h'

Signed-off-by: Mauricio Vásquez <mauricio@kinvolk.io>