add WindowsDriver to llvm_raw_libs
Upstream https://reviews.llvm.org/D118070 added a new
llvm raw lib LLVMWindowsDriver and this caused bcc
compilation error like below:

  ...
  /home/yhs/work/bcc/build/src/cc/libbcc.so: undefined reference to
    `llvm::getUniversalCRTSdkDir(llvm::vfs::FileSystem&,
     llvm::Optional<llvm::StringRef>, llvm::Optional<llvm::StringRef>,
     llvm::Optional<llvm::StringRef>,
     std::__cxx11::basic_string<char, std::char_traits<char>,
     std::allocator<char> >&,
     std::__cxx11::basic_string<char, std::char_traits<char>,
     std::allocator<char> >&)'
  /home/yhs/work/bcc/build/src/cc/libbcc.so: undefined reference to
     `llvm::useUniversalCRT(llvm::ToolsetLayout,
      std::__cxx11::basic_string<char, std::char_traits<char>,
      std::allocator<char> > const&, llvm::Triple::ArchType,
      llvm::vfs::FileSystem&)'
  ...

Add this library explicitly for llvm >= 15 and
Compilation succeeded.

Signed-off-by: Yonghong Song <yhs@fb.com>