Do not assume any code-tables on strings
Scripts should never assume what codetable an external user has
and try to decode. Doing that has huge potential to cause pain and
misery for users (a common python3 sickness nowadays).

Traceback (most recent call last):
  File "../../tools/slabratetop.py", line 123, in <module>
    print("%-32s %6d %10d" % (k.name.decode(), v.count, v.size))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 2: ordinal not in range(128)

This patch removes all instances of decode and encode. This means it will have regressions on
python3 which will no longer work.