uprobe: Fix failed to attach BPF to uprobe error
./ugc <pid>
Sometimes errors may occur:
Traceback (most recent call last):
  File "/usr/share/bcc/tools/lib/./ugc", line 216, in <module>
    bpf = BPF(text=program, usdt_contexts=[usdt])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bpfcc/__init__.py", line 512, in __init__
    usdt_context.attach_uprobes(self, attach_usdt_ignore_pid)
  File "/usr/lib/python3.11/site-packages/bpfcc/usdt.py", line 209, in attach_uprobes
    bpf.attach_uprobe(name=binpath, fn_name=fn_name,
  File "/usr/lib/python3.11/site-packages/bpfcc/__init__.py", line 1417, in attach_uprobe
    raise Exception("Failed to attach BPF to uprobe")
Exception: Failed to attach BPF to uprobe

The error location is at IS_LIGHNED(ref_ctr_offset, sizeof(short)) of function __uprobe_register.
This is because the input of the bpf_attach_uprobe function in libbpf.c has increased,
but lib.bpf_attach_uprobe has not been modified,
resulting in ref_ctr_offset being a random number and potentially causing an error.

Fixes: 50f2009c7521 ("uprobe: Add ref_cnt_offset arg to
bpf_attach_uprobe")
Signed-off-by: Feng Yang <yangfeng@kylinos.cn>