Add strict LLVM 3.7.1 version check to CMakeLists.txt
Newer LLVM versions will cause build failure due to headers layout changes. Reproduced with llvm-4.0 on Ubuntu 16.04:
```
./bcc/src/cc/frontends/clang/loader.cc:35:37: fatal error: clang/Basic/FileManager.h: No such file or directory
```