build: use old libstdc++ ABI for GCC 5.1 and later
According to https://gcc.gnu.org/gcc-5/changes.html#libstdcxx,
GCC 5.1 and later introduce a dual ABI for C++ runtime library,
and the new ABI is enabled by default.

On Fedora 23 the version of gcc is 5.3.1, and the build of libbcc.so
and tests would fail with the following errors:

......
../../src/cc/libbcc.a(bpf_module.cc.o): In function `ebpf::BPFModule::dump_ir(llvm::Module&)':
bpf_module.cc:(.text+0x44c0): undefined reference to `llvm::createPrintModulePass(llvm::raw_ostream&,
	std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
../../src/cc/libbcc.a(bpf_module.cc.o): In function `llvm::RTDyldMemoryManager::findSymbol(
	std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
bpf_module.cc:(.text._ZN4llvm19RTDyldMemoryManager10findSymbolERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[
	_ZN4llvm19RTDyldMemoryManager10findSymbolERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x18):
undefined reference to `llvm::RTDyldMemoryManager::getSymbolAddressInProcess(
	std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
......

Fix it by adding -D_GLIBCXX_USE_CXX11_ABI=0 to CMAKE_CXX_FLAGS to
restore to the old ABI.