fix a llvm compilation error with llvm16
LLVM16 patch
  https://github.com/llvm/llvm-project/commit/b4e9977fc18405d4a11cbaf1975bcadbf75920b8
caused bcc build failure like below:

 from /.../bcc/src/cc/frontends/clang/b_frontend_action.cc:23:
 /.../llvm-project/llvm/build/install/include/llvm/ADT/StringRef.h:96:54: error: expected ‘)’ before ‘Str’
     /*implicit*/ constexpr StringRef(std::string_view Str)
                                     ~                ^~~~
                                                      )
 /.../llvm-project/llvm/build/install/include/llvm/ADT/StringRef.h:239:14: error: expected type-specifier
     operator std::string_view() const {
              ^~~

LLVM build itself now is done with c++17. Let us also compile with c++17
if bcc is built with llvm16.

Signed-off-by: Yonghong Song <yhs@fb.com>