Add missing sched.h include for CLONE_NEWNS
This fixes the compile with `-stdlib=libc++`. Without this header the build fails with:

```
../src/cc/ns_guard.cc:75:30: error: use of undeclared identifier 'CLONE_NEWNS'
```