Fix a build failure with clang21
The build error message:
  src/cc/frontends/clang/loader.cc:400:73: error: no matching function for
   call to ‘clang::TextDiagnosticPrinter::TextDiagnosticPrinter(
     llvm::raw_fd_ostream&, clang::DiagnosticOptions*)’
  400 |   auto diag_client = new TextDiagnosticPrinter(llvm::errs(), &*diag_opts);
      |                                                                         ^
The llvm commit
  https://github.com/llvm/llvm-project/pull/139584
caused the build failure.

Adjust the code properly and the error is fixed.